<?php

namespace AppBundle\Repository;

/**
 * MailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailRepository extends \Doctrine\ORM\EntityRepository {

    public function findAllNotSentMails() {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $getMails = $qb->select('m')
                ->from('AppBundle\Entity\Mail', 'm')
                ->where(
                        $qb->expr()->orX($qb->expr()->eq('m.isSent', 0), $qb->expr()->isNull('m.isSent'))
                )
                ->orderBy('m.priority', 'ASC')
                ->getQuery();
        return $getMails->getResult();
    }

}
